; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-- -mcpu=znver4 | FileCheck %s --check-prefixes=AVX512,ZNVER4
; RUN: llc < %s -mtriple=x86_64-- -mcpu=sapphirerapids | FileCheck %s --check-prefixes=AVX512,INTEL
; RUN: llc < %s -mtriple=x86_64-- -mcpu=cooperlake -mattr=-prefer-256-bit | FileCheck %s --check-prefixes=AVX512,INTEL
; RUN: llc < %s -mtriple=x86_64-- -mattr=+avx10.2 | FileCheck %s --check-prefixes=AVX10_2

; Don't fold sext/zext of a vXbf16 setcc into a setcc with a vXi16 result:
; VCMPBF16 only writes a mask register, and the f32-promoted compare of a
; v16bf16 would be a v16f32 CMPP, which has no non-mask form.

define <16 x i16> @fcmp_olt_v16bf16_sext(<16 x bfloat> %a, <16 x bfloat> %b) {
; ZNVER4-LABEL: fcmp_olt_v16bf16_sext:
; ZNVER4:       # %bb.0:
; ZNVER4-NEXT:    vpmovzxwd {{.*#+}} zmm1 = ymm1[0],zero,ymm1[1],zero,ymm1[2],zero,ymm1[3],zero,ymm1[4],zero,ymm1[5],zero,ymm1[6],zero,ymm1[7],zero,ymm1[8],zero,ymm1[9],zero,ymm1[10],zero,ymm1[11],zero,ymm1[12],zero,ymm1[13],zero,ymm1[14],zero,ymm1[15],zero
; ZNVER4-NEXT:    vpmovzxwd {{.*#+}} zmm0 = ymm0[0],zero,ymm0[1],zero,ymm0[2],zero,ymm0[3],zero,ymm0[4],zero,ymm0[5],zero,ymm0[6],zero,ymm0[7],zero,ymm0[8],zero,ymm0[9],zero,ymm0[10],zero,ymm0[11],zero,ymm0[12],zero,ymm0[13],zero,ymm0[14],zero,ymm0[15],zero
; ZNVER4-NEXT:    vpslld $16, %zmm1, %zmm1
; ZNVER4-NEXT:    vpslld $16, %zmm0, %zmm0
; ZNVER4-NEXT:    vcmpltps %zmm1, %zmm0, %k0
; ZNVER4-NEXT:    vpmovm2w %k0, %ymm0
; ZNVER4-NEXT:    retq
;
; INTEL-LABEL: fcmp_olt_v16bf16_sext:
; INTEL:       # %bb.0:
; INTEL-NEXT:    vpmovzxwd {{.*#+}} zmm1 = ymm1[0],zero,ymm1[1],zero,ymm1[2],zero,ymm1[3],zero,ymm1[4],zero,ymm1[5],zero,ymm1[6],zero,ymm1[7],zero,ymm1[8],zero,ymm1[9],zero,ymm1[10],zero,ymm1[11],zero,ymm1[12],zero,ymm1[13],zero,ymm1[14],zero,ymm1[15],zero
; INTEL-NEXT:    vpslld $16, %zmm1, %zmm1
; INTEL-NEXT:    vpmovzxwd {{.*#+}} zmm0 = ymm0[0],zero,ymm0[1],zero,ymm0[2],zero,ymm0[3],zero,ymm0[4],zero,ymm0[5],zero,ymm0[6],zero,ymm0[7],zero,ymm0[8],zero,ymm0[9],zero,ymm0[10],zero,ymm0[11],zero,ymm0[12],zero,ymm0[13],zero,ymm0[14],zero,ymm0[15],zero
; INTEL-NEXT:    vpslld $16, %zmm0, %zmm0
; INTEL-NEXT:    vcmpltps %zmm1, %zmm0, %k0
; INTEL-NEXT:    vpmovm2w %k0, %ymm0
; INTEL-NEXT:    retq
;
; AVX10_2-LABEL: fcmp_olt_v16bf16_sext:
; AVX10_2:       # %bb.0:
; AVX10_2-NEXT:    vcmpltbf16 %ymm1, %ymm0, %k0
; AVX10_2-NEXT:    vpmovm2w %k0, %ymm0
; AVX10_2-NEXT:    retq
  %c = fcmp olt <16 x bfloat> %a, %b
  %r = sext <16 x i1> %c to <16 x i16>
  ret <16 x i16> %r
}

define void @fcmp_olt_v16bf16_sext_store(ptr %out, ptr %pa, ptr %pb) {
; AVX512-LABEL: fcmp_olt_v16bf16_sext_store:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpmovzxwd {{.*#+}} zmm0 = mem[0],zero,mem[1],zero,mem[2],zero,mem[3],zero,mem[4],zero,mem[5],zero,mem[6],zero,mem[7],zero,mem[8],zero,mem[9],zero,mem[10],zero,mem[11],zero,mem[12],zero,mem[13],zero,mem[14],zero,mem[15],zero
; AVX512-NEXT:    vpmovzxwd {{.*#+}} zmm1 = mem[0],zero,mem[1],zero,mem[2],zero,mem[3],zero,mem[4],zero,mem[5],zero,mem[6],zero,mem[7],zero,mem[8],zero,mem[9],zero,mem[10],zero,mem[11],zero,mem[12],zero,mem[13],zero,mem[14],zero,mem[15],zero
; AVX512-NEXT:    vpslld $16, %zmm1, %zmm1
; AVX512-NEXT:    vpslld $16, %zmm0, %zmm0
; AVX512-NEXT:    vcmpltps %zmm1, %zmm0, %k0
; AVX512-NEXT:    vpmovm2w %k0, %ymm0
; AVX512-NEXT:    vmovdqu %ymm0, (%rdi)
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
;
; AVX10_2-LABEL: fcmp_olt_v16bf16_sext_store:
; AVX10_2:       # %bb.0:
; AVX10_2-NEXT:    vmovdqu (%rsi), %ymm0
; AVX10_2-NEXT:    vcmpltbf16 (%rdx), %ymm0, %k0
; AVX10_2-NEXT:    vpmovm2w %k0, %ymm0
; AVX10_2-NEXT:    vmovdqu %ymm0, (%rdi)
; AVX10_2-NEXT:    vzeroupper
; AVX10_2-NEXT:    retq
  %a = load <16 x bfloat>, ptr %pa, align 2
  %b = load <16 x bfloat>, ptr %pb, align 2
  %c = fcmp olt <16 x bfloat> %a, %b
  %r = sext <16 x i1> %c to <16 x i16>
  store <16 x i16> %r, ptr %out, align 2
  ret void
}

define <16 x i16> @fcmp_olt_v16bf16_zext(<16 x bfloat> %a, <16 x bfloat> %b) {
; ZNVER4-LABEL: fcmp_olt_v16bf16_zext:
; ZNVER4:       # %bb.0:
; ZNVER4-NEXT:    vpmovzxwd {{.*#+}} zmm1 = ymm1[0],zero,ymm1[1],zero,ymm1[2],zero,ymm1[3],zero,ymm1[4],zero,ymm1[5],zero,ymm1[6],zero,ymm1[7],zero,ymm1[8],zero,ymm1[9],zero,ymm1[10],zero,ymm1[11],zero,ymm1[12],zero,ymm1[13],zero,ymm1[14],zero,ymm1[15],zero
; ZNVER4-NEXT:    vpmovzxwd {{.*#+}} zmm0 = ymm0[0],zero,ymm0[1],zero,ymm0[2],zero,ymm0[3],zero,ymm0[4],zero,ymm0[5],zero,ymm0[6],zero,ymm0[7],zero,ymm0[8],zero,ymm0[9],zero,ymm0[10],zero,ymm0[11],zero,ymm0[12],zero,ymm0[13],zero,ymm0[14],zero,ymm0[15],zero
; ZNVER4-NEXT:    vpslld $16, %zmm1, %zmm1
; ZNVER4-NEXT:    vpslld $16, %zmm0, %zmm0
; ZNVER4-NEXT:    vcmpltps %zmm1, %zmm0, %k0
; ZNVER4-NEXT:    vpmovm2w %k0, %ymm0
; ZNVER4-NEXT:    vpsrlw $15, %ymm0, %ymm0
; ZNVER4-NEXT:    retq
;
; INTEL-LABEL: fcmp_olt_v16bf16_zext:
; INTEL:       # %bb.0:
; INTEL-NEXT:    vpmovzxwd {{.*#+}} zmm1 = ymm1[0],zero,ymm1[1],zero,ymm1[2],zero,ymm1[3],zero,ymm1[4],zero,ymm1[5],zero,ymm1[6],zero,ymm1[7],zero,ymm1[8],zero,ymm1[9],zero,ymm1[10],zero,ymm1[11],zero,ymm1[12],zero,ymm1[13],zero,ymm1[14],zero,ymm1[15],zero
; INTEL-NEXT:    vpslld $16, %zmm1, %zmm1
; INTEL-NEXT:    vpmovzxwd {{.*#+}} zmm0 = ymm0[0],zero,ymm0[1],zero,ymm0[2],zero,ymm0[3],zero,ymm0[4],zero,ymm0[5],zero,ymm0[6],zero,ymm0[7],zero,ymm0[8],zero,ymm0[9],zero,ymm0[10],zero,ymm0[11],zero,ymm0[12],zero,ymm0[13],zero,ymm0[14],zero,ymm0[15],zero
; INTEL-NEXT:    vpslld $16, %zmm0, %zmm0
; INTEL-NEXT:    vcmpltps %zmm1, %zmm0, %k0
; INTEL-NEXT:    vpmovm2w %k0, %ymm0
; INTEL-NEXT:    vpsrlw $15, %ymm0, %ymm0
; INTEL-NEXT:    retq
;
; AVX10_2-LABEL: fcmp_olt_v16bf16_zext:
; AVX10_2:       # %bb.0:
; AVX10_2-NEXT:    vcmpltbf16 %ymm1, %ymm0, %k0
; AVX10_2-NEXT:    vpmovm2w %k0, %ymm0
; AVX10_2-NEXT:    vpsrlw $15, %ymm0, %ymm0
; AVX10_2-NEXT:    retq
  %c = fcmp olt <16 x bfloat> %a, %b
  %r = zext <16 x i1> %c to <16 x i16>
  ret <16 x i16> %r
}

define <8 x i16> @fcmp_olt_v8bf16_sext(<8 x bfloat> %a, <8 x bfloat> %b) {
; ZNVER4-LABEL: fcmp_olt_v8bf16_sext:
; ZNVER4:       # %bb.0:
; ZNVER4-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; ZNVER4-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; ZNVER4-NEXT:    vpslld $16, %ymm1, %ymm1
; ZNVER4-NEXT:    vpslld $16, %ymm0, %ymm0
; ZNVER4-NEXT:    vcmpltps %ymm1, %ymm0, %k0
; ZNVER4-NEXT:    vpmovm2w %k0, %xmm0
; ZNVER4-NEXT:    vzeroupper
; ZNVER4-NEXT:    retq
;
; INTEL-LABEL: fcmp_olt_v8bf16_sext:
; INTEL:       # %bb.0:
; INTEL-NEXT:    vpmovzxwd {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero
; INTEL-NEXT:    vpslld $16, %ymm1, %ymm1
; INTEL-NEXT:    vpmovzxwd {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero
; INTEL-NEXT:    vpslld $16, %ymm0, %ymm0
; INTEL-NEXT:    vcmpltps %ymm1, %ymm0, %k0
; INTEL-NEXT:    vpmovm2w %k0, %xmm0
; INTEL-NEXT:    vzeroupper
; INTEL-NEXT:    retq
;
; AVX10_2-LABEL: fcmp_olt_v8bf16_sext:
; AVX10_2:       # %bb.0:
; AVX10_2-NEXT:    vcmpltbf16 %xmm1, %xmm0, %k0
; AVX10_2-NEXT:    vpmovm2w %k0, %xmm0
; AVX10_2-NEXT:    retq
  %c = fcmp olt <8 x bfloat> %a, %b
  %r = sext <8 x i1> %c to <8 x i16>
  ret <8 x i16> %r
}
